# https://pre-commit.com
# https://pre-commit.com/hooks.html

default_language_version:
  python: python3.10
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: check-docstring-first
      - id: no-commit-to-branch
        args: [--branch, main]
  - repo: local
    hooks:
      - id: check-rej-files
        name: Check for .rej files
        entry: >
          bash -c "REJ_FILES=$(git diff --name-only --cached | grep '\.rej$'); if [ -n \"$REJ_FILES\" ]; then exit 1; fi;"

        language: system
  - repo: https://github.com/python-poetry/poetry
    rev: 1.8.4
    hooks:
      - id: poetry-check
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.4
    hooks:
      - id: ruff
        args: [--select, I, --fix]
      - id: ruff-format
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.4
    hooks:
      - id: actionlint
  - repo: https://github.com/google/yamlfmt
    rev: v0.14.0
    hooks:
      - id: yamlfmt
